/*
 * This source file was generated by the Gradle 'init' task
 */
package logger.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Logger logger = Logger.getInstance();
        assertNotNull(logger);
    }
}
