/*
 * This source file was generated by the Gradle 'init' task
 */
package singleton;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        
        
    }
}
