/*
 * This source file was generated by the Gradle 'init' task
 */
package strategy.payments;

public class App {

    public static void main(String[] args) {
        PaymentProcess cardPayment = new PaymentProcess(new CardPayment());
        cardPayment.executePayment(100);

        PaymentProcess payPalPayment = new PaymentProcess(new PayPal());
        payPalPayment.executePayment(200);
    }
}
