/*
 * This source file was generated by the Gradle 'init' task
 */
package payment.options;

public class App {

    public static void main(String[] args) {
        Payment payment1 = PaymentFactory.getPaymentMethod("paypal");
        payment1.pay(100.0);

        Payment payment2 = PaymentFactory.getPaymentMethod("card");
        payment2.pay(200.0);
    }
}
