/*
 * This source file was generated by the Gradle 'init' task
 */
package logger.project;

public class App {
    
    public static void main(String[] args) {
          Logger logger = Logger.getInstance();

        logger.info("Application started");
        logger.debug("Loading user data...");
        logger.warn("Low memory warning");
        logger.error("Failed to open database connection");

        Logger logger2 = Logger.getInstance();
        logger2.info("Logger2 is the same instance as Logger");
    }
}
