/*
 * This source file was generated by the Gradle 'init' task
 */
package singleton;

public class App {

    public static void main(String[] args) {
        Car car = Car.getInstance();
        car.drive();
    }
}
