spring.application.name=project

spring.datasource.url=jdbc:mysql://localhost:3306/jobportal?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=4143@Katlego

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=8081

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=1005619065248-j0ohbblksh7s1atdk7gbr7s2gjl2buo4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
spring.security.oauth2.client.provider.google.user-name-attribute=sub

