/*
 * This source file was generated by the Gradle 'init' task
 */
package subscribe;

public class App {

    public static void main(String[] args) {
        Channel techChannel = new Channel("Tech News");
        Subscriber notification1 = new Subscriber("Alice");
        Subscriber notification2 = new Subscriber("Bob");
        Subscriber notification3 = new Subscriber("Charlie");

        techChannel.subscribe(notification1);
        techChannel.subscribe(notification2);
        techChannel.subscribe(notification3);

        System.out.println("Channel: " + techChannel.getName());

        techChannel.notifySubscribers("Welcome to Tech News Channel Users!");

        techChannel.unsubscribe(notification1);

        techChannel.notifySubscribers("Latest Tech Update Available!");
    }
}
